"""
Model 2: Mean Reverting Strategy.
Trades when market is in "Balance" state - price is trapped
within Value Area (ranging/consolidating).

Entry: False breakout of VA boundary + opposing order flow + return inside range.
Stop: Beyond the false breakout extreme (+ 1-2 ticks buffer).
Target: Opposite VA boundary or POC.
"""

import logging
from dataclasses import dataclass
from enum import Enum
from typing import Optional, Tuple

import pandas as pd

from config.settings import (
    RANGE_FIRST_DRIVE_BARS,
    RANGE_STOP_OFFSET_TICKS,
    RANGE_VA_BUFFER_TICKS,
    TICK_SIZE,
)
from src.engine.paper_trader import OrderSide
from src.indicators.cvd import CVDIndicator
from src.indicators.order_flow import OrderFlowAnalyzer
from src.indicators.volume_profile import VolumeProfileResult

logger = logging.getLogger(__name__)


class BreakoutState(Enum):
    NONE = "NONE"
    FIRST_DRIVE = "FIRST_DRIVE"
    RETURNED = "RETURNED"
    FALSE_BREAKOUT = "FALSE_BREAKOUT"


@dataclass
class RangeSignal:
    """Signal generated by the range model."""

    active: bool = False
    direction: str = ""  # "LONG" or "SHORT"
    entry_price: float = 0.0
    stop_loss: float = 0.0
    take_profit: float = 0.0
    confidence: float = 0.0
    reason: str = ""


class RangeModel:
    """
    Model 2: Mean Reverting.

    Logic:
    1. Confirm market is ranging within Value Area (5m)
    2. Detect exit beyond VAH/VAL boundary
    3. Skip first drive (never trade first breakout)
    4. Wait for price to return inside VA (false breakout)
    5. Confirm with opposing aggressive order flow
    6. Enter on return into range
    """

    def __init__(self):
        self.of = OrderFlowAnalyzer()
        self.cvd = CVDIndicator()
        self.va_buffer = RANGE_VA_BUFFER_TICKS * TICK_SIZE
        self.stop_offset = RANGE_STOP_OFFSET_TICKS * TICK_SIZE

        # Track breakout state
        self._breakout_state_high = BreakoutState.NONE
        self._breakout_state_low = BreakoutState.NONE
        self._first_drive_high_count = 0
        self._first_drive_low_count = 0
        self._breakout_extreme_high = 0.0
        self._breakout_extreme_low = float("inf")

    def reset_state(self):
        """Reset breakout tracking state."""
        self._breakout_state_high = BreakoutState.NONE
        self._breakout_state_low = BreakoutState.NONE
        self._first_drive_high_count = 0
        self._first_drive_low_count = 0
        self._breakout_extreme_high = 0.0
        self._breakout_extreme_low = float("inf")

    def is_ranging(
        self, data_5m: pd.DataFrame, vp: VolumeProfileResult
    ) -> bool:
        """
        Step 1: Check if market is ranging within Value Area.
        """
        if data_5m.empty or vp.vah == 0:
            return False

        recent = data_5m.tail(10)
        bars_in_va = (
            (recent["close"] >= vp.val - self.va_buffer)
            & (recent["close"] <= vp.vah + self.va_buffer)
        ).sum()

        is_range = bars_in_va >= 6  # 60%+ of bars within VA (relaxed from 7)

        logger.info(
            "[RANGE] Ranging check: %d/10 bars in VA (VAL=%.2f, VAH=%.2f, buf=%.2f) -> %s",
            bars_in_va, vp.val, vp.vah, self.va_buffer,
            "RANGING" if is_range else "NOT RANGING",
        )
        return is_range

    def update_breakout_tracking(
        self,
        data_1m: pd.DataFrame,
        vp: VolumeProfileResult,
    ) -> None:
        """
        Step 2 & 3: Track breakout attempts and skip first drives.
        """
        if data_1m.empty or vp.vah == 0:
            return

        current = data_1m.iloc[-1]
        price = current["close"]
        high = current["high"]
        low = current["low"]

        # --- VAH (upside) breakout tracking ---
        if high > vp.vah + self.va_buffer:
            if self._breakout_state_high == BreakoutState.NONE:
                self._breakout_state_high = BreakoutState.FIRST_DRIVE
                self._first_drive_high_count = 0
                self._breakout_extreme_high = high
                logger.info("[RANGE] VAH first drive detected at %.2f (VAH=%.2f)", high, vp.vah)

            elif self._breakout_state_high == BreakoutState.FIRST_DRIVE:
                self._first_drive_high_count += 1
                self._breakout_extreme_high = max(self._breakout_extreme_high, high)

            elif self._breakout_state_high == BreakoutState.RETURNED:
                self._breakout_state_high = BreakoutState.FALSE_BREAKOUT
                self._breakout_extreme_high = max(self._breakout_extreme_high, high)
                logger.info("[RANGE] VAH FALSE BREAKOUT detected at %.2f", high)

        elif price < vp.vah:
            if self._breakout_state_high in (
                BreakoutState.FIRST_DRIVE,
                BreakoutState.FALSE_BREAKOUT,
            ):
                if self._first_drive_high_count >= RANGE_FIRST_DRIVE_BARS:
                    self._breakout_state_high = BreakoutState.RETURNED
                    logger.info("[RANGE] VAH breakout returned inside VA (count=%d)", self._first_drive_high_count)

        # --- VAL (downside) breakout tracking ---
        if low < vp.val - self.va_buffer:
            if self._breakout_state_low == BreakoutState.NONE:
                self._breakout_state_low = BreakoutState.FIRST_DRIVE
                self._first_drive_low_count = 0
                self._breakout_extreme_low = low
                logger.info("[RANGE] VAL first drive detected at %.2f (VAL=%.2f)", low, vp.val)

            elif self._breakout_state_low == BreakoutState.FIRST_DRIVE:
                self._first_drive_low_count += 1
                self._breakout_extreme_low = min(self._breakout_extreme_low, low)

            elif self._breakout_state_low == BreakoutState.RETURNED:
                self._breakout_state_low = BreakoutState.FALSE_BREAKOUT
                self._breakout_extreme_low = min(self._breakout_extreme_low, low)
                logger.info("[RANGE] VAL FALSE BREAKOUT detected at %.2f", low)

        elif price > vp.val:
            if self._breakout_state_low in (
                BreakoutState.FIRST_DRIVE,
                BreakoutState.FALSE_BREAKOUT,
            ):
                if self._first_drive_low_count >= RANGE_FIRST_DRIVE_BARS:
                    self._breakout_state_low = BreakoutState.RETURNED
                    logger.info("[RANGE] VAL breakout returned inside VA (count=%d)", self._first_drive_low_count)

        # Log current state
        logger.info(
            "[RANGE] State: high=%s (count=%d, extreme=%.2f), low=%s (count=%d, extreme=%.2f)",
            self._breakout_state_high.value, self._first_drive_high_count,
            self._breakout_extreme_high,
            self._breakout_state_low.value, self._first_drive_low_count,
            self._breakout_extreme_low,
        )

    def evaluate(
        self,
        data_5m: pd.DataFrame,
        data_1m: pd.DataFrame,
        data_1m_flow: pd.DataFrame,
        vp: VolumeProfileResult,
        session: str = "LONDON",
    ) -> RangeSignal:
        """
        Full evaluation pipeline for Model 2.
        """
        signal = RangeSignal()

        # Step 1: Confirm ranging
        if not self.is_ranging(data_5m, vp):
            return signal

        # Step 2-3: Update breakout tracking
        self.update_breakout_tracking(data_1m, vp)

        current_price = data_1m.iloc[-1]["close"]

        # --- Check for SHORT signal (false breakout above VAH) ---
        if self._breakout_state_high == BreakoutState.RETURNED:
            if current_price < vp.vah:
                logger.info("[RANGE] Checking SHORT entry: price=%.2f < VAH=%.2f", current_price, vp.vah)

                triggered, entry_price, _ = self.of.detect_reversal_entry(
                    data_1m_flow, direction="SHORT", session=session
                )

                if triggered and entry_price is not None:
                    zone_signal = self.of.scan_zone(
                        data_1m_flow,
                        vp.vah - self.va_buffer,
                        self._breakout_extreme_high + self.va_buffer,
                        session=session,
                    )

                    if zone_signal.has_no_follow_through or zone_signal.net_aggression == "BEARISH":
                        stop_loss = self._breakout_extreme_high + self.stop_offset
                        take_profit = vp.poc

                        cvd_result = self.cvd.calculate(data_1m_flow)
                        cvd_confirms = cvd_result.cvd_trend in ("FALLING", "FLAT")
                        confidence = 0.7 if cvd_confirms else 0.5

                        signal = RangeSignal(
                            active=True,
                            direction="SHORT",
                            entry_price=entry_price,
                            stop_loss=stop_loss,
                            take_profit=take_profit,
                            confidence=confidence,
                            reason="Range SHORT: False VAH breakout + reversal flow",
                        )

                        self._breakout_state_high = BreakoutState.NONE
                        logger.info(
                            ">>> RANGE SIGNAL: SHORT @ %.2f | SL: %.2f | TP: %.2f",
                            entry_price, stop_loss, take_profit,
                        )
                        return signal
                    else:
                        logger.info("[RANGE] SHORT: no follow-through=%s, aggression=%s — skipping",
                                    zone_signal.has_no_follow_through, zone_signal.net_aggression)
                else:
                    logger.info("[RANGE] SHORT: no reversal entry trigger detected")

        # --- Check for LONG signal (false breakout below VAL) ---
        if self._breakout_state_low == BreakoutState.RETURNED:
            if current_price > vp.val:
                logger.info("[RANGE] Checking LONG entry: price=%.2f > VAL=%.2f", current_price, vp.val)

                triggered, entry_price, _ = self.of.detect_reversal_entry(
                    data_1m_flow, direction="LONG", session=session
                )

                if triggered and entry_price is not None:
                    zone_signal = self.of.scan_zone(
                        data_1m_flow,
                        self._breakout_extreme_low - self.va_buffer,
                        vp.val + self.va_buffer,
                        session=session,
                    )

                    if zone_signal.has_no_follow_through or zone_signal.net_aggression == "BULLISH":
                        stop_loss = self._breakout_extreme_low - self.stop_offset
                        take_profit = vp.poc

                        cvd_result = self.cvd.calculate(data_1m_flow)
                        cvd_confirms = cvd_result.cvd_trend in ("RISING", "FLAT")
                        confidence = 0.7 if cvd_confirms else 0.5

                        signal = RangeSignal(
                            active=True,
                            direction="LONG",
                            entry_price=entry_price,
                            stop_loss=stop_loss,
                            take_profit=take_profit,
                            confidence=confidence,
                            reason="Range LONG: False VAL breakout + reversal flow",
                        )

                        self._breakout_state_low = BreakoutState.NONE
                        logger.info(
                            ">>> RANGE SIGNAL: LONG @ %.2f | SL: %.2f | TP: %.2f",
                            entry_price, stop_loss, take_profit,
                        )
                        return signal
                    else:
                        logger.info("[RANGE] LONG: no follow-through=%s, aggression=%s — skipping",
                                    zone_signal.has_no_follow_through, zone_signal.net_aggression)
                else:
                    logger.info("[RANGE] LONG: no reversal entry trigger detected")

        return signal
