"""
Model 1: Trend Following Strategy.
Trades when market is in "Out of Balance" state - price has broken
out of previous Value Area and moves impulsively.

Entry: Pullback to LVN + aggressive order flow confirmation + 1m candle close.
Stop: Below/above aggression cluster.
Target: Previous POC or day extreme.
"""

import logging
from dataclasses import dataclass
from typing import Optional, Tuple

import numpy as np
import pandas as pd

from config.settings import (
    TICK_SIZE,
    TREND_BREAKEVEN_TICKS,
    TREND_LVN_PROXIMITY_TICKS,
)
from src.engine.paper_trader import OrderSide
from src.indicators.cvd import CVDIndicator, CVDResult
from src.indicators.order_flow import OrderFlowAnalyzer
from src.indicators.volume_profile import VolumeProfile, VolumeProfileResult

logger = logging.getLogger(__name__)


@dataclass
class TrendSignal:
    """Signal generated by the trend model."""

    active: bool = False
    direction: str = ""  # "LONG" or "SHORT"
    entry_price: float = 0.0
    stop_loss: float = 0.0
    take_profit: float = 0.0
    confidence: float = 0.0
    reason: str = ""


class TrendModel:
    """
    Model 1: Trend Following.

    Logic:
    1. Detect breakout from previous Value Area (5m timeframe)
    2. Find LVN in the impulse move (local volume profile)
    3. Wait for pullback to LVN zone
    4. Confirm with aggressive order flow on 1m
    5. Enter on confirming candle close
    """

    def __init__(self):
        self.vp = VolumeProfile()
        self.of = OrderFlowAnalyzer()
        self.cvd = CVDIndicator()
        self.lvn_proximity = TREND_LVN_PROXIMITY_TICKS * TICK_SIZE

    def detect_breakout(
        self,
        data_5m: pd.DataFrame,
        prev_vp: VolumeProfileResult,
    ) -> Tuple[bool, str]:
        """
        Step 1: Detect if market has broken out of previous Value Area.
        Returns (is_breakout, direction).
        """
        if data_5m.empty or prev_vp.vah == 0:
            return False, ""

        current_price = data_5m.iloc[-1]["close"]
        recent = data_5m.tail(5)

        # Price clearly above previous VAH = bullish breakout
        if current_price > prev_vp.vah:
            bars_above = (recent["close"] > prev_vp.vah).sum()
            logger.info(
                "[TREND] Breakout check UP: price=%.2f > VAH=%.2f, bars_above=%d/5 (need 3)",
                current_price, prev_vp.vah, bars_above,
            )
            if bars_above >= 3:
                return True, "LONG"

        # Price clearly below previous VAL = bearish breakout
        if current_price < prev_vp.val:
            bars_below = (recent["close"] < prev_vp.val).sum()
            logger.info(
                "[TREND] Breakout check DOWN: price=%.2f < VAL=%.2f, bars_below=%d/5 (need 3)",
                current_price, prev_vp.val, bars_below,
            )
            if bars_below >= 3:
                return True, "SHORT"

        # Log why no breakout
        logger.info(
            "[TREND] No breakout: price=%.2f, VAH=%.2f, VAL=%.2f (price inside VA or insufficient bars)",
            current_price, prev_vp.vah, prev_vp.val,
        )
        return False, ""

    def find_impulse_lvn(
        self,
        data_1m: pd.DataFrame,
        direction: str,
    ) -> list:
        """
        Step 2: Find LVN in the recent impulse move.
        Builds local volume profile on the impulse and returns LVN levels.
        """
        if len(data_1m) < 10:
            return []

        # Identify impulse: look for directional move in last 30-60 bars
        recent = data_1m.tail(60)

        if direction == "LONG":
            low_idx = recent["low"].idxmin()
            impulse = recent.loc[low_idx:]
        else:
            high_idx = recent["high"].idxmax()
            impulse = recent.loc[high_idx:]

        if len(impulse) < 3:
            logger.info("[TREND] Impulse too short: %d bars", len(impulse))
            return []

        # Calculate local volume profile on impulse
        local_vp = self.vp.calculate(impulse)
        logger.info(
            "[TREND] Impulse LVN: %d levels found in %d-bar impulse (range %.2f-%.2f)",
            len(local_vp.lvn_levels), len(impulse),
            impulse["low"].min(), impulse["high"].max(),
        )
        return local_vp.lvn_levels

    def check_pullback_to_lvn(
        self,
        current_price: float,
        lvn_levels: list,
        direction: str,
    ) -> Optional[float]:
        """
        Step 3: Check if price has pulled back to any LVN level.
        Returns the LVN level if price is near it, None otherwise.
        """
        closest_lvn = None
        closest_dist = float("inf")

        for lvn in lvn_levels:
            distance = abs(current_price - lvn)
            if distance < closest_dist:
                closest_dist = distance
                closest_lvn = lvn

            if distance <= self.lvn_proximity:
                logger.info(
                    "[TREND] Price at LVN! price=%.2f, LVN=%.2f, dist=%.2f (max=%.2f)",
                    current_price, lvn, distance, self.lvn_proximity,
                )
                return lvn

        if closest_lvn is not None:
            logger.info(
                "[TREND] Closest LVN=%.2f, dist=%.2f, proximity=%.2f — %s",
                closest_lvn, closest_dist, self.lvn_proximity,
                "TOO FAR" if closest_dist > self.lvn_proximity else "OK",
            )
        return None

    def evaluate(
        self,
        data_5m: pd.DataFrame,
        data_1m: pd.DataFrame,
        data_1m_flow: pd.DataFrame,
        prev_vp: VolumeProfileResult,
        session: str = "NY",
    ) -> TrendSignal:
        """
        Full evaluation pipeline for Model 1.
        Returns a TrendSignal if all conditions are met.
        """
        signal = TrendSignal()

        # Step 1: Check for breakout
        is_breakout, direction = self.detect_breakout(data_5m, prev_vp)
        if not is_breakout:
            return signal

        logger.info("[TREND] === BREAKOUT DETECTED: %s ===", direction)

        # Step 2: Find LVN levels in impulse
        lvn_levels = self.find_impulse_lvn(data_1m, direction)
        if not lvn_levels:
            logger.info("[TREND] No LVN levels found, skipping")
            return signal

        # Step 3: Check pullback to LVN
        current_price = data_1m.iloc[-1]["close"]
        active_lvn = self.check_pullback_to_lvn(current_price, lvn_levels, direction)
        if active_lvn is None:
            return signal

        # Step 4: Check order flow for aggressive entry
        side_str = "LONG" if direction == "LONG" else "SHORT"
        triggered, entry_price, stop_price = self.of.detect_trend_entry(
            data_1m_flow, direction=side_str, session=session
        )

        if not triggered or entry_price is None or stop_price is None:
            logger.info(
                "[TREND] At LVN but no order flow trigger (need aggressive %s candle)",
                direction,
            )
            return signal

        # CVD confirmation
        cvd_result = self.cvd.calculate(data_1m_flow)
        cvd_confirms = (
            (direction == "LONG" and cvd_result.cvd_trend in ("RISING", "FLAT"))
            or (direction == "SHORT" and cvd_result.cvd_trend in ("FALLING", "FLAT"))
        )

        confidence = 0.7 if cvd_confirms else 0.5

        # Step 5: Calculate targets
        if direction == "LONG":
            take_profit = max(
                data_5m["high"].max(),
                prev_vp.poc if prev_vp.poc > entry_price else data_5m["high"].max(),
            )
            stop_loss = stop_price - TICK_SIZE
        else:
            take_profit = min(
                data_5m["low"].min(),
                prev_vp.poc if prev_vp.poc < entry_price else data_5m["low"].min(),
            )
            stop_loss = stop_price + TICK_SIZE

        signal = TrendSignal(
            active=True,
            direction=direction,
            entry_price=entry_price,
            stop_loss=stop_loss,
            take_profit=take_profit,
            confidence=confidence,
            reason=f"Trend {direction}: LVN pullback + aggressive order flow"
            + (" + CVD confirm" if cvd_confirms else ""),
        )

        logger.info(
            "TREND SIGNAL: %s @ %.2f | SL: %.2f | TP: %.2f | Conf: %.0f%%",
            direction,
            entry_price,
            stop_loss,
            take_profit,
            confidence * 100,
        )

        return signal
